In [1]:
"""
This notebook runs the examples of Section Complexes of Height Functions  
"""

import sSet
import numpy as np


In [2]:
def print_reeb(X, num_lvl, dim_homology):
    """
    Computes and prints boundary matrices of dim_homology-th Reeb complexes of a given simplicial set with height
    
    Parameters
    ----------
    X : SimplicialSetWithHeight
        Input simplicial set
    num_lvl : int
        number of height levels to compute
    dim_homology : tuple
        tuple of dimensions to compute
    """
    for dim in dim_homology:
        r = sSet.reeb_complex(X,dim,num_lvl)
        print('Boundary matrices of ' + str(dim) + '-th Reeb complex')
        for lvl in range(num_lvl):
            print('delta_' + str(lvl+1))
            boundmat = np.zeros_like(r[lvl][0])
            for k, horizontal_face_maps in enumerate(r[lvl]):
                boundmat += np.multiply(np.power(-1, k), horizontal_face_maps)
            print(boundmat)
            print('')

In [3]:
print("Example 3.3: Simplicial model for the 2-sphere, gluing two 2-simplices")
# Define 0-, 1- and 2-simplices with given heights and create simplicial set with height
v_0 = sSet.SimplexWithHeight(None, [0])
v_1 = sSet.SimplexWithHeight(None, [1])
v_2 = sSet.SimplexWithHeight(None, [2])
e_01 = sSet.SimplexWithHeight([v_1, v_0], [0, 1])
e_02 = sSet.SimplexWithHeight([v_2, v_0], [0, 2])
e_12 = sSet.SimplexWithHeight([v_2, v_1], [1, 2])
t_012_0 = sSet.SimplexWithHeight([e_12, e_02, e_01], [0, 1, 2])
t_012_1 = sSet.SimplexWithHeight([e_12, e_02, e_01], [0, 1, 2])

X = sSet.SimplicialSetWithHeight([v_0, v_1, v_2], 
                                 [e_01,e_02, e_12],
                                 [t_012_0, t_012_1])
# Compute boundary matrices of 0th reeb complex, with simplices across 3 heights
print_reeb(X, 2, (0,))

Example 3.3: Simplicial model for the 2-sphere, gluing two 2-simplices
Boundary matrices of 0-th Reeb complex
delta_1
[[-1. -1.  0.]
 [ 1.  0. -1.]
 [ 0.  1.  1.]]

delta_2
[[ 1.  1.]
 [-1. -1.]
 [ 1.  1.]]



In [4]:
print("Example 3.5: Simplicial model for the 2-sphere, gluing two subdivided 2-simplices")
# Define 0-, 1- and 2-simplices with given heights and create simplicial set with height
v_0 = sSet.SimplexWithHeight(None, [0])
v_1_0 = sSet.SimplexWithHeight(None, [1])
v_1_1 = sSet.SimplexWithHeight(None, [1])
v_2 = sSet.SimplexWithHeight(None, [2])
e_01_0 = sSet.SimplexWithHeight([v_1_0, v_0], [0, 1])
e_01_1 = sSet.SimplexWithHeight([v_1_1, v_0], [0, 1])
e_11_0 = sSet.SimplexWithHeight([v_1_0, v_1_1], [1, 1])
e_11_1 = sSet.SimplexWithHeight([v_1_1, v_1_0], [1, 1])
e_12_0 = sSet.SimplexWithHeight([v_2, v_1_0], [1, 2])
e_12_1 = sSet.SimplexWithHeight([v_2, v_1_1], [1, 2])
t_011_0 = sSet.SimplexWithHeight([e_11_0, e_01_0, e_01_1], [0, 1, 1])
t_011_1 = sSet.SimplexWithHeight([e_11_1, e_01_1, e_01_0], [0, 1, 1])
t_112_0 = sSet.SimplexWithHeight([e_12_1, e_12_0, e_11_1], [1, 1, 2])
t_112_1 = sSet.SimplexWithHeight([e_12_0, e_12_1, e_11_0], [1, 1, 2])

X = sSet.SimplicialSetWithHeight([v_0, v_1_0, v_1_1, v_2], 
                                 [e_01_0, e_01_1, e_11_0, 
                                  e_11_1, e_12_0, e_12_1],
                                 [t_011_0, t_011_1, t_112_0, t_112_1])
# Compute boundary matrices of 0th and 1st reeb complex, with simplices across 2 heights
print_reeb(X, 1, (0,1))

Example 3.5: Simplicial model for the 2-sphere, gluing two subdivided 2-simplices
Boundary matrices of 0-th Reeb complex
delta_1
[[-1.  0.]
 [ 1. -1.]
 [ 0.  1.]]

Boundary matrices of 1-th Reeb complex
delta_1
[[ 1. -1.]]



In [5]:
print("Example 3.12: Simplicial model for the cylinder")
# Define 0-, 1- and 2-simplices with given heights and create simplicial set with height
v_00 = sSet.SimplexWithHeight(None, [0])
v_01 = sSet.SimplexWithHeight(None, [0])
v_02 = sSet.SimplexWithHeight(None, [0])
v_10 = sSet.SimplexWithHeight(None, [1])
v_11 = sSet.SimplexWithHeight(None, [1])
v_20 = sSet.SimplexWithHeight(None, [2])
v_21 = sSet.SimplexWithHeight(None, [2])
v_22 = sSet.SimplexWithHeight(None, [2])
e_00_01 = sSet.SimplexWithHeight([v_01, v_00], [0,0])
e_00_12 = sSet.SimplexWithHeight([v_02, v_01], [0,0])
e_00_20 = sSet.SimplexWithHeight([v_00, v_02], [0,0])
e_01_00 = sSet.SimplexWithHeight([v_10, v_00], [0,1])
e_01_11 = sSet.SimplexWithHeight([v_11, v_01], [0,1])
e_01_10 = sSet.SimplexWithHeight([v_10, v_01], [0,1])
e_01_21 = sSet.SimplexWithHeight([v_11, v_02], [0,1])
e_01_20 = sSet.SimplexWithHeight([v_10, v_02], [0,1])
e_02_21 = sSet.SimplexWithHeight([v_21, v_02], [0,2])
e_02_22 = sSet.SimplexWithHeight([v_22, v_02], [0,2])
e_02_20 = sSet.SimplexWithHeight([v_20, v_02], [0,2])
e_11_01 = sSet.SimplexWithHeight([v_11, v_10], [1,1])
e_12_00 = sSet.SimplexWithHeight([v_20, v_10], [1,2])
e_12_11 = sSet.SimplexWithHeight([v_21, v_11], [1,2])
e_12_10 = sSet.SimplexWithHeight([v_20, v_11], [1,2])
e_22_01 = sSet.SimplexWithHeight([v_21, v_20], [2,2])
e_22_12 = sSet.SimplexWithHeight([v_22, v_21], [2,2])
e_22_20 = sSet.SimplexWithHeight([v_20, v_22], [2,2])
t_001_010 = sSet.SimplexWithHeight([e_01_10, e_01_00, e_00_01], [0,0,1])
t_001_121 = sSet.SimplexWithHeight([e_01_21, e_01_11, e_00_12], [0,0,1])
t_001_200 = sSet.SimplexWithHeight([e_01_00, e_01_20, e_00_20], [0,0,1])
t_011_101 = sSet.SimplexWithHeight([e_11_01, e_01_11, e_01_10], [0,1,1])
t_012_211 = sSet.SimplexWithHeight([e_12_11, e_02_21, e_01_21], [0,1,2])
t_012_200 = sSet.SimplexWithHeight([e_12_00, e_02_20, e_01_20], [0,1,2])
t_022_212 = sSet.SimplexWithHeight([e_22_12, e_02_22, e_02_21], [0,2,2])
t_022_220 = sSet.SimplexWithHeight([e_22_20, e_02_20, e_02_22], [0,2,2])
t_112_010 = sSet.SimplexWithHeight([e_12_10, e_12_00, e_11_01], [1,1,2])
t_122_101 = sSet.SimplexWithHeight([e_22_01, e_12_11, e_12_10], [1,2,2])

X = sSet.SimplicialSetWithHeight([v_00, v_01, v_02,v_10, v_11, v_20, v_21, v_22],                                 
                                 [e_00_01, e_00_12, e_00_20, e_01_00, e_01_11, e_01_10, e_01_21, e_01_20, e_02_21, 
                                  e_02_22, e_02_20, e_11_01, e_12_00,e_12_11,e_12_10, e_22_01, e_22_12, e_22_20],
                                 [t_001_010, t_001_121, t_001_200, t_011_101, t_012_211, 
                                  t_012_200, t_022_212, t_022_220, t_112_010, t_122_101])
# Compute boundary matrices of 0th reeb complex, with simplices across 3 heights
print_reeb(X, 2, (0,))

Example 3.12: Simplicial model for the cylinder
Boundary matrices of 0-th Reeb complex
delta_1
[[-1. -1.  0.]
 [ 1.  0. -1.]
 [ 0.  1.  1.]]

delta_2
[[ 1.  1.]
 [-1. -1.]
 [ 1.  1.]]



In [6]:
print("Example 4.5: Pinched cylinder")
# Define 0-, 1- and 2-simplices with given heights and create simplicial set with height
v_0 = sSet.SimplexWithHeight(None, [0])
u_1 = sSet.SimplexWithHeight(None, [1])
e_00_0 = sSet.SimplexWithHeight([v_0, v_0], [0,0])
e_00_1 = sSet.SimplexWithHeight([v_0, v_0], [0,0])
e_01_0 = sSet.SimplexWithHeight([u_1, v_0], [0,1])
e_01_1 = sSet.SimplexWithHeight([u_1, v_0], [0,1])
e_01_2 = sSet.SimplexWithHeight([u_1, v_0], [0,1])
e_01_3 = sSet.SimplexWithHeight([u_1, v_0], [0,1])
e_11_0 = sSet.SimplexWithHeight([u_1, u_1], [1,1])
e_11_1 = sSet.SimplexWithHeight([u_1, u_1], [1,1])
t_001_0 = sSet.SimplexWithHeight([e_01_3, e_01_2, e_00_0], [0,0,1])
t_001_1 = sSet.SimplexWithHeight([e_01_0, e_01_1, e_00_1], [0,0,1])
t_011_0 = sSet.SimplexWithHeight([e_11_1, e_01_2, e_01_0], [0,1,1])
t_011_1 = sSet.SimplexWithHeight([e_11_0, e_01_1, e_01_3], [0,1,1])

X = sSet.SimplicialSetWithHeight([v_0,u_1],                                 
                                 [e_00_0, e_00_1, e_01_0, e_01_1, e_01_2, e_01_3, e_11_0, e_11_1],
                                 [t_001_0, t_001_1, t_011_0, t_011_1])
# Compute boundary matrices of 0th and 1st reeb complexes, with simplices across 2 heights
print_reeb(X, 1, (0,1))

Example 4.5: Pinched cylinder
Boundary matrices of 0-th Reeb complex
delta_1
[[-1.]
 [ 1.]]

Boundary matrices of 1-th Reeb complex
delta_1
[[-1.]
 [-1.]
 [ 1.]
 [ 1.]]

